FROM node:12.13.0-alpine

WORKDIR /app

RUN apk update && \
    npm install -g npm && \
    npm install -g @vue/cli \
    npm install -g @vue/cli-init \
    npm install -g firebase-tools

CMD ["/bin/ash"]
